[package]
name = "async_logger"
version = "0.1.0"
authors = ["TYPEmber <nono02200059@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
yansi = "0.5"
chrono = "0.4"